# those files are needed for both, deseq and metilene, they are specified in
# the shared Snakefile dir
api_manifest:
  - gdc_manifest_20211029_data_release_31.0_active.tsv.gz

#md5sum_mani:
#  - 26d406d171e43f470ba338f4ec480cc0

#gtf_UUID:
#  - 25aa497c-e615-4cb7-8751-71f744f9691f

#md5sum_gtf:
#  - 291330bdcff1094bc4d5645de35e0871
