manifest_file:
  - gdc_manifest_20211029_data_release_31.0_active.tsv.gz

gtf:
  - gencode.v36.annotation.gtf.gz

gdc_manifest_20211029_data_release_31.0_active.tsv.gz:  # outfilename
  - gdc_manifest_20211029_data_release_31.0_active.tsv.gz # filename on server
  - 26d406d171e43f470ba338f4ec480cc0  # md5
  - https://docs.gdc.cancer.gov/Data/Release_Notes/  # url

gencode.v36.annotation.gtf.gz:  # outfilename
  - 25aa497c-e615-4cb7-8751-71f744f9691f  # filename on server (a name or a UUID)
  - 291330bdcff1094bc4d5645de35e0871  # md5sum
  - https://api.gdc.cancer.gov/data
